# Download a Ubuntu Image
FROM ubuntu:latest

# Set TimeZone
RUN apt-get update && apt-get install -y tzdata
ENV TZ=Europe/Madrid
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Update & Upgrade Repository
RUN apt-get update && apt-get upgrade -y

# Install Python
RUN apt-get install -y software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update \
    && apt-get install -y python3.12 python3.12-venv python3.12-dev

# Install pip
RUN python3.12 -m venv /jf


# Install Google API dependencies
RUN /jf/bin/pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

# Install Pandas Library
RUN /jf/bin/pip install pandas

# Install openpyxl
RUN /jf/bin/pip install openpyxl

# Install python-dotenv
RUN /jf/bin/pip install python-dotenv

# Copy Python Files & json files & .env file
COPY *.py /alpha/
COPY *.json /alpha/
COPY .env /alpha/

# Copy Excel Files
COPY /files/*.xlsx /alpha/files/


# Move to the working directory
WORKDIR /alpha

# Execute python script
CMD ["/bin/bash", "-c", "\
while [ $(date +%H) -lt 22 ]; do \
    /jf/bin/python /alpha/JotformData.py; \
    sleep 600; \
done"]

